<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_offset" value="0.048"/>
  <xacro:property name="base_size_x" value="0.432"/>
  <xacro:property name="base_size_y" value="0.384"/>
  <xacro:property name="base_size_z" value="0.024"/>
  <xacro:property name="wheel_length" value="0.016"/>
  <xacro:property name="wheel_radius" value="0.048"/>
  <xacro:property name="wheel_separation" value="0.424"/>
  <xacro:property name="wheel_offset_x" value="-0.168"/>
  <xacro:property name="wheel_offset_y" value="0"/>
  <xacro:property name="wheel_offset_z" value="0"/>
  <xacro:property name="caster_wheel_radius" value="0.048"/>
  <xacro:property name="caster_wheel_offset_x" value="0.168"/>
  <xacro:property name="caster_wheel_offset_y" value="0"/>
  <xacro:property name="caster_wheel_offset_z" value="0"/>
  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_size_x} ${base_size_y} 0.002"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>
  <joint name="base_link_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_offset}" rpy="0 0 0"/>
  </joint>
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>
  <joint name="l_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="l_wheel"/>
    <origin xyz="${wheel_offset_x} ${wheel_offset_y+wheel_separation/2} ${wheel_offset_z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="l_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  <joint name="r_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="r_wheel"/>
    <origin xyz="${wheel_offset_x} ${wheel_offset_y-wheel_separation/2} ${wheel_offset_z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2"/>
  </joint>
  <link name="r_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${caster_wheel_offset_x} ${caster_wheel_offset_y} ${caster_wheel_offset_z}" rpy="0 0 0"/>
  </joint>
  <link name="caster_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>
</robot>
