ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    two_d_mode: true
    publish_tf: true
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    map_frame: map
    initial_state: [-4.0, 3.0, 0.0,
                     0.0, 0.0, 0.0,
                     0.1, 0.2, 0.3,
                     0.0, 0.0, 0.0,
                     0.0, 0.0, 0.0]
    odom0: /diff_drive_controller/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_differential: true
    imu0: /bno055/imu
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true, false, false]
    imu0_differential: false
